# Generated by Django 4.1.7 on 2023-02-21 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todotask', '0003_alter_task_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='user_slug',
            field=models.SlugField(blank=True, default=None, null=True, unique=True),
        ),
    ]
