# Generated by Django 4.1.7 on 2023-02-21 22:18

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todotask', '0005_alter_task_options_task_complete_task_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='user_slug',
            field=autoslug.fields.AutoSlugField(default=None, editable=False, null=True, populate_from='title', unique=True),
        ),
    ]
